name: release

on:
  workflow_dispatch:
    inputs:
      gcc_version:
        required: true
        type: string
        
      binutils_version:
        required: true
        type: string
    
      gdb_version:
        required: true
        type: string

jobs:
  i686:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: build
      run: docker run -v "${{ github.workspace }}:/root" --rm lordmilko/i686-elf-tools -parallel -gv ${{ inputs.gcc_version }} -bv ${{ inputs.binutils_version }} -dv ${{ inputs.gdb_version }}

    - uses: actions/upload-artifact@v3
      with:
        name: i686-elf-tools
        path: ${{ github.workspace }}/build-i686-elf/*.zip

  x86_64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build
      run: docker run -v "${{ github.workspace }}:/root" --rm lordmilko/i686-elf-tools -parallel -gv ${{ inputs.gcc_version }} -bv ${{ inputs.binutils_version }} -dv ${{ inputs.gdb_version }} -64

    - uses: actions/upload-artifact@v3
      with:
        name: x86_64-elf-tools
        path: ${{ github.workspace }}/build-x86_64-elf/*.zip
